#!/bin/bash
chmo -R +x .#!/bin/bash
chmo -R +x .#!/bin/bash
chmo -R +x .#!/bin/bash
chmo -R +x .#!/bin/bash
chmo -R +x .#!/bin/bash
chmo -R +x .#!/bin/bash
chmo -R +x .#!/bin/bash
chmo -R +x .#!/bin/bash
chmo -R +x .
